version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: hello-api:latest
    container_name: hello-api
    ports:
      - "8000:8000"
    environment:
      - APP_ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./hello-api.db
    volumes:
      - ../app:/app/app:ro  # Montar el código como solo lectura
      - hello-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - hello-network

networks:
  hello-network:
    driver: bridge

volumes:
  hello-data:
    driver: local