# Template for the Deployment of the Python application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-birthday.fullname" . }}
  labels:
    {{- include "hello-birthday.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-birthday.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-birthday.selectorLabels" . | nindent 8 }}
      annotations:
        # Annotation for the OpenTelemetry collector to discover this pod
        app.kubernetes.io/name: hello-birthday
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000 # The port exposed by the app in the Dockerfile
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http