# Template for the Service that exposes the application within the cluster.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-birthday.fullname" . }}
  labels:
    {{- include "hello-birthday.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-birthday.selectorLabels" . | nindent 4 }}